<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash; // Usado para senhas, se necessário
use App\Models\Animal; // Importa o Model Animal

class AnimalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Limpa a tabela antes de inserir para evitar duplicatas ao rodar o seeder novamente
        DB::table('animais')->truncate();

        $animais = [
            [
                'user_id' => 1,
                'tipo' => 'Cachorro',
                'nome' => 'Muttley',
                'raca' => 'Vira-Lata',
                'cor' => 'Caramelo',
                'sexo' => 'Macho',
                'tam' => 'Grande',
                'imagem1' => 'imagem1.png',
                'imagem2' => 'imagem2.png',
                'imagem3' => 'imagem3.png',
                'imagem4' => 'imagem4.png',
                'aparencia' => 'Ele é magro e a cor da barriga é branco',
                'lugar_visto' => 'Rua Exemplo da Silva',
                'lugar_encontrado' => 'Rua Exemplo de Oliveira',
                'status' => 'resolvido',
                'situacao' => 'Encontrado',
            ],
            [
                'user_id' => 1,
                'tipo' => 'Gato',
                'nome' => 'Mel',
                'raca' => 'Maine Coon',
                'cor' => 'Cinza',
                'sexo' => 'Fêmea',
                'tam' => 'Medio',
                'imagem1' => 'https://cdn2.thecatapi.com/images/MTY3ODIyMQ.jpg',
                'status' => 'resolvido',
                'situacao' => 'Encontrado',
            ],
            [
                'user_id' => 2,
                'nome' => 'Spike',
                'tipo' => 'Cachorro',
                'raca' => 'Labrador',
                'cor' => 'Marrom',
                'sexo' => 'Macho',
                'tam' => 'Grande',
                'imagem1' => 'https://adotar.com.br/upload/2023-04/animais_imagem979687.jpg?w=700&format=webp',
                'imagem2' => 'https://cruzarcachorro.com.br/imagens/produto/1/2853.jpg',
                'imagem3' => 'https://i.pinimg.com/736x/9c/67/38/9c6738bf74f94adf5ed0f9e4170cbf2d.jpg',
                'imagem4' => 'https://adnchocolate.com.ar/wp-content/uploads/como-son-las-hembras-labrador.webp',
                'aparencia' => 'pelo marrom escuro quase preto, o focinho é mais claro que o pelo',
                'lugar_visto' => 'Av. João Olímpio de Oliveira, Vila Asem, Itapetininga - SP',
                'status' => 'ativo',
                'situacao' => 'Perdido',
            ],
            [
                'user_id' => 2,
                //'nome' => '', // Sem nome
                'tipo' => 'Gato',
                'raca' => 'Siamês',
                'cor' => 'Preto e creme',
                'sexo' => 'Fêmea',
                'tam' => 'Medio',
                'imagem1' => 'https://adotar.com.br/upload/2024-04/animais_imagem1112099.jpg?w=700&format=webp',
                'imagem2' => 'https://adotar.com.br/upload/2024-04/animais_imagem1112078.jpeg?w=700&format=webp',
                'imagem3' => 'https://adotar.com.br/upload/2024-04/animais_imagem1112079.jpeg?w=700&format=webp',
                'imagem4' => 'https://adotar.com.br/upload/2024-04/animais_imagem1112076.jpeg?w=115&format=webp',
                'aparencia' => 'entre a parte clara e a parte escura tem um tom de marrom com cinza',
                'lugar_encontrado' => 'Rua Olívia da Silva de Oliveira',
                'status' => 'ativo',
                'situacao' => 'Encontrado',
            ],
            [
                'user_id' => 1,
                'tipo' => 'Gato',
                //'nome' => '(sem coleira)',
                'raca' => 'Siamês',
                'cor' => 'Branco e cinza',
                'sexo' => 'Fêmea',
                'imagem1' => 'https://adotar.com.br/upload/2016-07/animais_imagem200048.jpg?w=700&format=webp',
                //'status' => 'pendente',
                'situacao' => 'Encontrado',
            ],
            [
                'user_id' => 1,
                'tipo' => 'Cachorro',
                'nome' => 'Max',
                'raca' => 'Labrador',
                'cor' => 'Preto',
                'sexo' => 'Macho',
                'tam' => 'Pequeno',
                'imagem1' => 'imagem1.png',
                'imagem2' => 'imagem2.png',
                'imagem3' => 'imagem3.png',
                'imagem4' => 'imagem4.png',
                'aparencia' => 'Fihote com uma coleira azul com símbolo de osso',
                'lugar_encontrado' => 'Rua Sílvia de Oliveira da Silva',
                //'status' => 'pendente',
                'situacao' => 'Encontrado',
            ],
            [
                'user_id' => 1,
                'tipo' => 'Gato',
                //'nome' => '(sem coleira)',
                'raca' => 'Persa',
                'cor' => 'Cinza',
                'sexo' => 'Macho',
                'imagem1' => 'https://img.olx.com.br/images/25/252444316710330.jpg',
                //'status' => 'pendente',
                'situacao' => 'Encontrado',
            ],
            [
                'user_id' => 1,
                'tipo' => 'Cachorro',
                'nome' => 'Luna',
                'raca' => 'Akbash',
                'cor' => 'Branco',
                'sexo' => 'Fêmea',
                'imagem1' => 'https://cdn.pixabay.com/photo/2018/12/09/14/58/dog-3865029_1280.jpg',
                //'status' => 'pendente',
                'situacao' => 'Encontrado',
            ],
            [
                'user_id' => 1,
                'nome' => 'Qiqi',
                'tipo' => 'Cachorro',
                'raca' => 'Pastor-Alemão',
                'cor' => 'Cinza',
                'sexo' => 'Fêmea',
                'tam' => 'Grande',
                'imagem1' => 'https://i.pinimg.com/474x/f2/9d/ba/f29dba2b270a670bc0f604692762cf91.jpg',
                'imagem2' => 'https://mega.ibxk.com.br/2018/11/08/gafanhoto-08120353817089.jpg?ims=fit-in/800x500',
                'imagem3' => 'https://i.redd.it/izj5qxtyjuze1.jpeg',
                'imagem4' => 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQPhKXN4cGJl2MCAsyIozhLZBAnyDIBmYszyE1GAHIBlLYylcjU',
                'aparencia' => 'Orelhas peludas, olhos azuis, parecido com um lobo',
                'lugar_visto' => 'Praça Dos Três Poderes',
                //'status' => 'pendente',
                'situacao' => 'Perdido',
            ],
            [
                'user_id' => 1,
                'tipo' => 'Cachorro',
                'nome' => 'Bento',
                'raca' => 'Vira-Lata',
                'cor' => 'Tricolor',
                'sexo' => 'Macho',
                'imagem1' => 'https://adotar.com.br/upload/2024-09/animais_imagem1155164.jpg?w=700&format=webp',
                'status' => 'ativo',
                'situacao' => 'Encontrado',
            ],
            [
                'user_id' => 1,
                'tipo' => 'Cachorro',
                'nome' => 'Zeca',
                'raca' => 'Beagle',
                'cor' => 'Tricolor',
                'sexo' => 'Macho',
                'imagem1' => 'https://love.doghero.com.br/wp-content/uploads/2016/10/Beagle-6-1024x768.jpg',
                'status' => 'ativo',
                'situacao' => 'Encontrado',
            ],
            [
                'user_id' => 1,
                'tipo' => 'Cachorro',
                //'nome' => '',
                'raca' => 'Labrador',
                'cor' => 'Branco',
                'sexo' => 'Fêmea',
                'imagem1' => 'https://cdn.jornaldaparaiba.com.br/wp-content/uploads/2024/01/racas-de-cachorro-labrador-retriever.jpg?xid=650493',
                'status' => 'ativo',
                'situacao' => 'Encontrado',
            ],
            [
                'user_id' => 1,
                'tipo' => 'Gato',
                'nome' => 'Lua',
                'raca' => 'Frajola',
                'cor' => 'Branco e Preto',
                'sexo' => 'Fêmea',
                'imagem1' => 'https://cdn.pixabay.com/photo/2020/04/27/23/52/black-cat-5102116_1280.jpg',
                'status' => 'ativo',
                'situacao' => 'Perdido',
            ],
            [
                'user_id' => 1,
                'tipo' => 'Cachorro',
                'nome' => 'Laika',
                'raca' => 'Vira-Lata',
                'cor' => 'Preto/Branco',
                'sexo' => 'Fêmea',
                'imagem1' => 'https://redacao.labmidia.com.br/wp-content/uploads/2024/09/raca-de-cachorro-para-fazenda-1.jpg',
                'status' => 'ativo',
                'situacao' => 'Perdido',
            ],
            [
                'user_id' => 1,
                'tipo' => 'Cachorro',
                'nome' => 'Shicha',
                'raca' => 'dachshund',
                'cor' => 'Preto',
                'sexo' => 'Macho',
                'imagem1' => 'https://www.adoropets.com.br/wp-content/uploads/2018/04/dachshund-grama.jpg',
                'status' => 'ativo',
                'situacao' => 'Perdido',
            ],
            [
                'user_id' => 1,
                'tipo' => 'Cachorro',
                'nome' => 'Thor',
                'raca' => 'Golden Retriever',
                'cor' => 'Dourado',
                'sexo' => 'Macho',
                'imagem1' => 'https://images.dog.ceo/breeds/retriever-golden/n02099601_3004.jpg',
                'status' => 'inativo',
                'situacao' => 'Perdido',
            ],
            [
                'user_id' => 1,
                'tipo' => 'Gato',
                'nome' => 'Maya',
                'raca' => 'Vira-Lata',
                'cor' => 'Tigrado Cinza',
                'sexo' => 'Fêmea',
                'aparencia' => 'Tem olhos amarelos quase verde e na parte do pescoço o pelo é branco',
                'imagem1' => 'https://cdn.shopify.com/s/files/1/0500/8965/6473/files/pexels-arina-krasnikova-7726295_480x480.jpg?v=1663249037',
                'imagem2' => 'https://media.istockphoto.com/id/479483795/pt/foto/prateado-gato-malhado-pussy.jpg?s=170667a&w=0&k=20&c=1czp9zs7YlqGRlk-p1LaM--zWF9vNI5HjuDgPrrYYZI=',
                'imagem3' => 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSv4_S_4ZEVQE5fPCnWeaUHaYYsW3nmpYBlELXNE5XOUyE7Uhok',
                'imagem4' => 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTX8aFA3Ef5nCoMdFOn829H85yOHhvUy0TzL8UK9sSNiCXhbhEZ',
                'lugar_visto' => 'R. 30 de Fevereiro',
                'status' => 'inativo',
                'situacao' => 'Perdido',
            ],
            [
                'user_id' => 1,
                'tipo' => 'Cachorro',
                'nome' => 'Rex',
                'raca' => 'Pitbull',
                'cor' => 'Cinza',
                'sexo' => 'Macho',
                'imagem1' => 'https://i.ytimg.com/vi/sAWu14YKrLY/sddefault.jpg',
                'status' => 'inativo',
                'situacao' => 'Perdido',
            ],
            [
                'user_id' => 1,
                'tipo' => 'Gato',
                'nome' => 'Frajola',
                'raca' => 'Vira-Lata',
                'cor' => 'Preto e Branco',
                'sexo' => 'Macho',
                'imagem1' => 'https://cobasiblog.blob.core.windows.net/production-ofc/2023/01/gato-preto-branco-frajola.png',
                'status' => 'inativo',
                'situacao' => 'Perdido',
            ],
            [
                'user_id' => 1,
                'tipo' => 'Cachorro',
                'nome' => 'Tibúrcio',
                'raca' => 'Vira-Lata',
                'cor' => 'Caramelo',
                'sexo' => 'Macho',
                'tam' => 'Grande',
                'aparencia' => 'Olhos escuros e barriga clara',
                'lugar_visto' => 'Rua Exemplo da Silva',
                'lugar_encontrado' => 'Rua Exemplo de Oliveira',
                'status' => 'resolvido',
                'situacao' => 'Perdido',
            ],
            [
                'user_id' => 1,
                'tipo' => 'Cachorro',
                'nome' => 'Chica',
                'raca' => 'Labrador',
                'cor' => 'Dourado',
                'sexo' => 'Fêmea',
                'tam' => 'Grande',
                'aparencia' => 'a cor do pelo é parecido com de frango assado',
                'lugar_visto' => 'Rua Exemplo da Silva',
                'lugar_encontrado' => 'Rua Exemplo de Oliveira',
                'status' => 'resolvido',
                'situacao' => 'Perdido',
            ],
            [
                'user_id' => 1,
                'tipo' => 'Cachorro',
                'nome' => 'Morcego',
                'raca' => 'Vira-Lata',
                'cor' => 'Preto',
                'sexo' => 'Macho',
                'tam' => 'Grande',
                'aparencia' => 'pelo curto totalmente preto e olhos castanhos claros',
                'lugar_visto' => 'Rua Exemplo da Silva',
                'lugar_encontrado' => 'Rua Exemplo de Oliveira',
                'status' => 'resolvido',
                'situacao' => 'Perdido',
            ],


        ];

        // Itera sobre o array e insere cada animal no banco de dados
        foreach ($animais as $animalData) {
            // Adiciona timestamps automaticamente
            $animalData['created_at'] = now();
            $animalData['updated_at'] = now();
            DB::table('animais')->insert($animalData);
        }
    }
}
